In [1]:
import pickle as pkl

In [2]:
def read_pickle(f):
    return pkl.load(open(f, 'rb'))

In [4]:
import pandas as pd

df = pd.read_pickle('pickle/cue.p')
df = pd.DataFrame(df)
df.head()

0    \
0  [0, 1, 2, 3, 1, 3, 1, 3, 3, 3, 1, 1, 3, 1, 3, ...   
1  [[1.189782638623508, -4.943260849969928], [1.3...   
2                                                  4   

                                                 1    \
0  [2, 0, 1, 2, 4, 2, 0, 2, 2, 2, 3, 0, 2, 0, 2, ...   
1  [[1.1387946438057281, -4.876500836917417], [1....   
2                                                  5   

                                                 2    \
0  [3, 3, 0, 2, 2, 2, 0, 4, 4, 4, 1, 0, 4, 0, 4, ...   
1  [[1.1387946438057281, -4.876500836917417], [1....   
2                                                  6   

                                                 3    \
0  [1, 2, 3, 1, 1, 1, 2, 4, 1, 1, 0, 1, 3, 1, 1, ...   
1  [[1.0464293862842156, -4.653846183260871], [0....   
2                                                  7   

                                                 4    \
0  [1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, ...   
1  [[1.0464293862842156, -4.653846183260871], [0....   
2                                                  2   

                                                 5    \
0  [1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, ...   
1  [[1.0464293862842156, -4.653846183260871], [0....   
2                                                  3   

                                                 6    \
0  [1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1, 1, ...   
1  [[1.2858685344893934, -4.345174998865242], [0....   
2                                                  4   

                                                 7    \
0  [1, 2, 3, 1, 1, 1, 1, 4, 1, 1, 0, 1, 5, 1, 1, ...   
1  [[1.2858685344893934, -4.345174998865242], [0....   
2                                                  7   

                                                 8    \
0  [1, 2, 3, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, ...   
1  [[1.2858685344893934, -4.345174998865242], [0....   
2                                                  5   

                                                 9    ...  \
0  [1, 1, 2, 1, 1, 1, 1, 3, 1, 3, 0, 1, 3, 1, 1, ...  ...   
1  [[1.4420773081886873, -4.403699508745622], [0....  ...   
2                                                  4  ...   

                                                 271  \
0  [0, 0, 2, 0, 0, 1, 0, 1, 1, 1, 2, 0, 1, 0, 1, ...   
1  [[0.534307282837877, -6.686556702363237], [-0....   
2                                                  3   

                                                 272  \
0  [0, 0, 2, 0, 0, 1, 0, 1, 1, 1, 2, 0, 1, 0, 1, ...   
1  [[0.534307282837877, -6.686556702363237], [-0....   
2                                                  4   

                                                 273  \
0  [0, 0, 2, 0, 0, 1, 0, 1, 1, 1, 2, 0, 1, 0, 1, ...   
1  [[0.534307282837877, -6.686556702363237], [-0....   
2                                                  4   

                                                 274  \
0  [0, 0, 2, 0, 0, 0, 0, 1, 1, 1, 2, 0, 1, 0, 1, ...   
1  [[0.534307282837877, -6.686556702363237], [-0....   
2                                                  4   

                                                 275  \
0  [0, 0, 2, 0, 0, 1, 0, 1, 1, 1, 2, 0, 1, 0, 1, ...   
1  [[0.534307282837877, -6.686556702363237], [-0....   
2                                                  4   

                                                 276  \
0  [1, 0, 2, 0, 0, 1, 0, 1, 1, 1, 2, 0, 4, 0, 1, ...   
1  [[0.92712788622434, -7.036536010363131], [-0.1...   
2                                                  5   

                                                 277  \
0  [1, 0, 2, 1, 5, 1, 2, 4, 1, 1, 2, 0, 4, 0, 1, ...   
1  [[0.92712788622434, -7.036536010363131], [-0.1...   
2                                                  6   

                                                 278  \
0  [5, 1, 2, 5, 5, 1, 5, 4, 1, 1, 2, 0, 4, 0, 1, ...   
1  [[0.8744469242590294, -7.295451845606165], [-0...   
2                                   

In [30]:
import pandas as pd

df = pd.read_pickle('data/network.p')
df = pd.DataFrame(df)
df.iloc[0]

0    [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...
Name: (2171, 02, a), dtype: object

In [27]:
import pandas as pd

df = pd.read_pickle('data/neural_activity.p')
df

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [ ]:
# aggregate the all entries in the row into one entry 

In [34]:
df.iloc[0].values

array([array([[0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              ...,
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.]])], dtype=object)

In [3]:
import numpy as np

array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

np.hstack([array_1, array_2])

array([ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15])

In [2]:
array_1

array([1, 2, 3, 4, 5])